### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by miron0xff** [kintama48/array_utils#1] opened 2022-08-31 16:23 UTC
Hi! I faced an error while using this library. 
In last block of code you have mixed tabs and spaces so Python throws an error:

```
File "/.../venv/lib/python3.9/site-packages/array_utils/code.py", line 22
    if endpoint:
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by kintama48** [comment] 2022-09-02 09:46
Hi Aleksandr!

Thanks for bringing this error to my attention. I made this library for a college project; I didn't think that someone would actually use it. Anyways, the issue is fixed now. 

Best regards,
Abdullah Baig

**Closed as completed by kintama48** 2022-09-02 09:46 UTC

**Comment by miron0xff** [comment] 2022-09-08 09:25
I've found your lib as a dependency in a project I'm in =)
